
name: Last Deploy Diff

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Download last successful commit hash to S3
      run: aws s3 cp s3://${{ secrets.AWS_BUCKET }}/last_successful_deploy.txt ./last_successful_deploy.txt
    
    - name: Set last commit hash to ENV
      run: echo "GITHUB_LAST_SUCCESS_REF=$(cat ./last_successful_deploy.txt)" >> $GITHUB_ENV
    
    - name: echo
      run: echo "git diff ${GITHUB_LAST_SUCCESS_REF} ${GITHUB_SHA}  --name-only"
    
    - name: echo
      run: git log
      
    - name: Print files changed btw last successful deploy and current run
      run: git diff ${GITHUB_LAST_SUCCESS_REF} ${GITHUB_SHA}  --name-only

    - name: Push last successful deploy commit hash to a artifact
      run: echo ${GITHUB_SHA} > ./last_successful_deploy.txt
    
    - name: Upload last successful commit hash to S3
      run: aws s3 cp ./last_successful_deploy.txt s3://${{ secrets.AWS_BUCKET }}/last_successful_deploy.txt

